# Generated by Django 3.0.2 on 2022-02-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='weather',
            field=models.CharField(db_index=True, max_length=2000, verbose_name='Название'),
        ),
    ]
