# Generated by Django 3.2.12 on 2022-03-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20220225_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='cities',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='weather',
            field=models.CharField(db_index=True, max_length=2000, verbose_name='weather'),
        ),
    ]
