# Generated by Django 3.2.12 on 2022-03-07 07:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_auto_20220305_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))], verbose_name='Longitude'),
        ),
    ]
